### ISSUE TITLE
Pre-select a given organization on the oauth landing page

### ISSUE THREAD

**Issue by seanders** [XeroAPI/xero-oauth2-omniauth-strategy#13]
Is it possible to pass in a parameter that will filter or pre-select a specific organization in this dropdown?

<img width="517" alt="image" src="https://user-images.githubusercontent.com/2849183/189011588-98a6cc21-f0fe-4849-bb9e-e7310c872e89.png">

I plan on using this to improve the user experience when a user is re-linking a connection that has since expired.

For example, consider this scenario:

A user is shown a call-to-action button in my application, urging them to re-link their Xero org.
When they click on the `Connect to Xero` button, the user shouldn't have to select the specific organization, since the user's intent is already know.

**Comment by seanders** [comment]
cc @jenksguo I searched around on the xero documentation, but I couldn't find anything on this topic.

**Comment by RettBehrens** [comment]
Hey @seanders unfortunately this is not something the Xero auth/consent screen is equipped to do. This package facilitates steps 1-5 of the OAuth2 flow as described in our [docs](https://developer.xero.com/documentation/guides/oauth2/auth-flow/)
