### ISSUE TITLE
Callback URL is not compatible with Omniauth 2

### ISSUE THREAD

**Issue by whithajess** [XeroAPI/xero-oauth2-omniauth-strategy#17]
Breaking change in Omniauth 2

- https://github.com/omniauth/omniauth/wiki/Upgrading-to-2.0#relative-root-apps
- https://github.com/omniauth/omniauth/pull/903

**Comment by whithajess** [comment]
@jenksguo I have made a PR for this and a few other issues that I noticed from your `1.0.2` release.

- https://github.com/XeroAPI/xero-oauth2-omniauth-strategy/pull/15
- https://github.com/XeroAPI/xero-oauth2-omniauth-strategy/pull/14

**Comment by RettBehrens** [comment]
Hey @whithajess thanks for picking these issues up. Jenks is no longer with Xero and no longer maintaining this repo. I'll be your point of contact going forward. I'm just getting the [sample app](https://github.com/XeroAPI/xero-oauth2-omniauth-sample) and the current package running locally. Will be looking into your PRs starting tomorrow

**Comment by whithajess** [comment]
Thanks for the heads up @RettBehrens much appreciated.

**Comment by RettBehrens** [comment]
Hey @whithajess looking at your PRs:

- #14 
- #15 
- #16 

Looks to me like all three of these can be merged and released as `1.0.3`.

Unfortunately There's not much in the way of documentation for this repo after Jenks left. Best I can tell is that for each new version he was adding the gem of the previous version to the [pkg](https://github.com/XeroAPI/xero-oauth2-omniauth-strategy/tree/master/pkg) folder and then cutting a release on github and publishing to ruby-gems. For example: current version is `1.0.2` but the most recent package version pkg folder is `1.0.1`

**Comment by whithajess** [comment]
Thanks for looking at these @RettBehrens I have pulled them all into a `1.0.3` release PR - https://github.com/XeroAPI/xero-oauth2-omniauth-strategy/pull/18

I didn't notice the `pkg` folder but this really isn't standard practice as these are all buildable from previous tags
- `1.0.2` is missing from this list also
I think its best to just remove this folder (which I have in the PR)

I have also made suggestions for cutting a release in the PR
