### ISSUE TITLE
Xero-oauth2 does not work along with devise oauth setup.

### ISSUE THREAD

**Issue by panuza** [XeroAPI/xero-oauth2-omniauth-strategy#6]
Ruby Version: 2.6.3
Rails Version: 5.1.7

I have my application setup with devise for authentication along with facebook provider. However when I add the `omniauth.rb` file and define the xero_oauth2 provider, I get `ActionController::RoutingError (No route matches [POST] "/auth/xero_oauth2")` error. But, it seems to work fine when I comment the routes for devise (facebook) and facebook omniauth setting.

Defined routes for devise:

```
devise_for :member, controllers: { :omniauth_callbacks => "member/omniauth_callbacks",
                                          registrations: 'member/registrations',
                                          sessions: 'member/sessions',
                                          passwords: 'member/passwords'
                                        }, path: 'member', path_names: { sign_in: 'login' }
```

Configuration in devise.rb

```
config.omniauth :facebook, ENV["OMNIAUTH_FACEBOOK_ID"], ENV["OMNIAUTH_FACEBOOK_SECRET"],
                  scope: 'email', secure_image_url: true, info_fields: 'email,first_name,last_name',
                  client_options: {
                    site: 'https://graph.facebook.com/v3.3',
                    authorize_url: "https://www.facebook.com/v3.3/dialog/oauth"
                  }
```

Omniauth.rb for xero_oauth2 provider setup

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider(
    :xero_oauth2,
    ENV['XERO_API_CLIENT_ID'],
    ENV['XERO_API_CLIENT_SECRET'],
    scope: 'openid profile email files accounting.transactions accounting.transactions.read accounting.reports.read accounting.journals.read accounting.settings accounting.settings.read accounting.contacts accounting.contacts.read accounting.attachments accounting.attachments.read offline_access',
    )
end
```
Error Message when I try to Connect to Xero:

`ActionController::RoutingError (No route matches [POST] "/auth/xero_oauth2"):`

**Comment by brownd7522** [comment]
I'm having a similar issue myself where I have users and admins. 

Admins are name spaced under /admin/ so I tried updating the initializer with below which also results in (No route matches [POST] "/auth/xero_oauth2")

```
configure do |config|
    config.path_prefix = '/admin/auth'
 end
```

**Comment by eadz** [comment]
The redirect URL will be something like `/members/auth/xero_oauth2` not just `/auth/xero_oauth2`

**Comment by eadz** [comment]
Also, if you read the devise omniauth documentation, you are NOT supposed to add the provider twice. Just add it once in initializers/devise.rb, not initializers/omniauth.rb as well.

**Comment by jenksguo** [comment]
@eadz @panuza sorry for not replying earlier. 

Since Omniauth 1.9.1 you will need to use POST form submission instead of GET redirection for initiating OAuth 2.0 app.

See example is available here: https://github.com/XeroAPI/xero-oauth2-omniauth-sample/blob/master/app/views/home/index.html.erb#L2-L4

Let me know if this works.
