### ISSUE TITLE
given name is nil if profile scope not requested

### ISSUE THREAD

**Issue by tataihono** [XeroAPI/xero-oauth2-omniauth-strategy#7]
https://github.com/XeroAPI/xero-oauth2-omniauth-strategy/blob/9e5a4d4260604c55d860c44abb7a3172ced19af7/lib/omniauth/strategies/xero_oauth2.rb#L32

If the scope does not include profile then `raw_info['given_name']` will be nil. This results in a `NoMethodError: undefined method + for nil:NilClass`.

This could probably be resolved by doing:
```Ruby
[raw_info['given_name'], raw_info['family_name']].compact.join(' ')
```

**Comment by jenksguo** [comment]
Hi @tataihono, sorry for not attending to the repo for so long. 

Thanks for your solution, v1.0.1 addressed it. 

![image](https://user-images.githubusercontent.com/41350731/113954391-14022f00-985d-11eb-8aa3-996c92e88cf4.png)

If you are in UK/AU/NZ/US please let me know your delivery address. I can send you an Xero developer T-shirt (jenks.guo@xero.com)
