### ISSUE TITLE
Releases and Tagging

### ISSUE THREAD

**Issue by whithajess** [XeroAPI/xero-oauth2-omniauth-strategy#9]
@jenksguo Thanks for the latest version `1.0.2` to allow `omniauth 2` - Makes it easy for us to upgrade in line with all our other libraries.

Is it possible to continue `Releases` and `Tagging` in GitHub it makes it a lot easier to see the change set and know whats been sent to `Rubygems`

**Comment by jenksguo** [comment]
Hey @whithajess, thanks for your feedback and the suggestion. 

I have created the [release and tag](https://github.com/XeroAPI/xero-oauth2-omniauth-strategy/releases/tag/v1.0.2). Much better developer experience this way. :-)

**Comment by whithajess** [comment]
Awesome much appreciated!
